# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/egh35/Documents/ECEC302/registerbank/registerbank.cache/wt [current_project]
set_property parent.project_path C:/Users/egh35/Documents/ECEC302/registerbank/registerbank.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib C:/Users/egh35/Documents/ECEC302/registerbank/registerbank.srcs/sources_1/new/regbank.vhd
read_xdc C:/Users/egh35/Downloads/basys3_master/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/egh35/Downloads/basys3_master/Basys3_Master.xdc]

synth_design -top regbank -part xc7a35tcpg236-1
write_checkpoint -noxdef regbank.dcp
catch { report_utilization -file regbank_utilization_synth.rpt -pb regbank_utilization_synth.pb }
