# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/egh35/Downloads/ECEC302 monday/ECEC302/ECEC302/serial_add_implement/serial_add_implement.cache/wt} [current_project]
set_property parent.project_path {C:/Users/egh35/Downloads/ECEC302 monday/ECEC302/ECEC302/serial_add_implement/serial_add_implement.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {{C:/Users/egh35/Downloads/ECEC302 monday/ECEC302/ECEC302/serial_add_implement/serial_add_implement.srcs/sources_1/new/serial_add.vhd}}
read_xdc {{C:/Users/egh35/Downloads/ECEC302 monday/ECEC302/ECEC302/serial_add_implement/serial_add_implement.srcs/sources_1/new/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/egh35/Downloads/ECEC302 monday/ECEC302/ECEC302/serial_add_implement/serial_add_implement.srcs/sources_1/new/Basys3_Master.xdc}}]

synth_design -top serial_adder -part xc7a35tcpg236-1
write_checkpoint -noxdef serial_adder.dcp
catch { report_utilization -file serial_adder_utilization_synth.rpt -pb serial_adder_utilization_synth.pb }
