# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/egh35/Downloads/ECEC302 monday/ECEC302/ECEC302/ORGATE/ORGATE.cache/wt} [current_project]
set_property parent.project_path {C:/Users/egh35/Downloads/ECEC302 monday/ECEC302/ECEC302/ORGATE/ORGATE.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/egh35/Downloads/ECEC302 monday/ECEC302/ECEC302/ORGATE/ORGATE.srcs/sources_1/new/orgate.vhd}
  {C:/Users/egh35/Downloads/ECEC302 monday/ECEC302/ECEC302/ORGATE/ORGATE.srcs/sources_1/new/orgateimp.vhd}
}
read_xdc {{C:/Users/egh35/Downloads/ECEC302 monday/ECEC302/ECEC302/ORGATE/ORGATE.srcs/constrs_1/new/constrs.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/egh35/Downloads/ECEC302 monday/ECEC302/ECEC302/ORGATE/ORGATE.srcs/constrs_1/new/constrs.xdc}}]

synth_design -top orgateimp -part xc7a35tcpg236-1
write_checkpoint -noxdef orgateimp.dcp
catch { report_utilization -file orgateimp_utilization_synth.rpt -pb orgateimp_utilization_synth.pb }
